Add database
IPilin/java-filmorate pull request #4
Opened 2022-11-05 21:56 UTC by IPilin

2022-11-06 23:11 UTC, IPilin commented
У меня нету тестов внутри самого гита 😭

2022-11-07 07:54 UTC, eugene-lenkevich requested changes
Привет, Алексей, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2022-11-07 07:54 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmGenreDaoImpl.java
> +                "LEFT JOIN genre AS g ON fg.genre_id = g.id " +
А имеет ли смысл вытаскивать записи для которых нет жанров, то есть нужен ли тут именно LEFT JOIN а не INNER? :)

2022-11-07 07:54 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmRatingDaoImpl.java
> +    public FilmRatingDaoImpl(JdbcTemplate jdbcTemplate) {
Можно не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor

2022-11-07 07:54 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public FilmGenre find(int id) throws IncorrectIdException {
int id - мне кажется что не особо очевидно что именно это за идентификатор, можно легко перепутать
лучгше будет если
а) дадим ему более говорящее имя
б) или будем передавать не ид, а целый объект, так чточно не ошибемся :)

2022-11-07 07:54 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            } catch (IncorrectIdException ignored) {            }
Мм, тоесть если упадет ошибка то о ней вообще нито знать не будет, а нужна ли она тогда, может как то сделать так чтобы ее вовсе не падало, а то получается вроде и ошибка, а вроде и нет, а зачем она тогда, хотя бы залогировать ? :)

2022-11-07 07:54 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        /* var user = find(user1);
Закоментированный код лучш не оставлять. Его потом трудно будет обратно приделать потому что, скорее всего, все вокруг поменяется, а для истории есть git :)

2022-11-14 09:40 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2022-11-19 16:59 UTC, merged